### ISSUE TITLE
Update db

### ISSUE THREAD

**Issue by Malkavianson** [minerdso/api-puxada#1]
**Antes de tudo**
Não reclamando, maravilhoso seu código e seu banco de dados
Porém, ele data de 2022

Como poderíamos baixar dados mais atualizados? Estou disposto a contribuir se for o caso!

Me manda dm no twitter @Aleehbest

**Comment by minerdso** [comment]
precisa de algum banco especifico fio?

cola ai no zap zap wa.me/11949356144
